# coding: utf-8
title: Análise de Dados - 2017.1
email: luiz.fonseca@ccc.ufcg.edu.br
description: >
  Torture the data, and it will confess to anything. ~ Ronald Coase, Economics, Nobel Prize Laureate
baseurl: /portfolio-data-analysis
url: http://fonluiz.github.io/portfolio-data-analysis # the base hostname & protocol for your site
github_username: fonluiz
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
